### ISSUE TITLE
Block pushes to master with failing CI

### ISSUE THREAD

**Issue by heinrichreimer** [Crazy-Marvin/MetadataRemover#10]
To keep the master branch healthy, would you consider protecting the master branch?
You can read more about it here: https://help.github.com/en/articles/about-protected-branches

**Comment by CrazyMarvin** [comment]
That's a fine idea. 
What do you think of the rule in the screenshot?

![master](https://user-images.githubusercontent.com/15004217/59067201-42093780-88b1-11e9-872d-a0770f3ce474.PNG)

**Comment by CrazyMarvin** [comment]
I checked _Require review from Code Owners_ and _Include administrators_.

![protection](https://user-images.githubusercontent.com/15004217/59098990-31dd7080-8922-11e9-90e3-dc90945e8265.PNG)

**Comment by heinrichreimer** [comment]
I would rather be a bit more strict.
In particular you could check "Dismiss stale PRs", "Require review from code owners" and "Include administrators".

**Comment by CrazyMarvin** [comment]
> 
> 
> I would rather be a bit more strict.
> In particular you could check "Dismiss stale PRs", "Require review from code owners" and "Include administrators".

Done. 👌

**Comment by heinrichreimer** [comment]
Very nice. Now meeting into Master should be safe thanks to code review and CI checks :+1:

**Comment by heinrichreimer** [comment]
Is there a reason why you didn't check "Dismiss stale PRs"?

**Comment by CrazyMarvin** [comment]
I checked _Dismiss stale pull requests_. The last screenshot is outdated.
Here is one I just took a few seconds ago. 😅 
![protection](https://user-images.githubusercontent.com/15004217/59145910-a4b21e80-89ea-11e9-96d2-d12bc0701933.PNG)

**Comment by heinrichreimer** [comment]
Just perfect 👏
