### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [Crazy-Marvin/MetadataRemover#104]
See https://f-droid.org/docs/Reproducible_Builds/#aboutlibraries-gradle-plugin.

**Comment by CrazyMarvin** [comment]
Thanks for the hint, @linsui.
May you please apply the fix, @Rashxz ?

**Comment by CrazyMarvin** [comment]
Thanks to @Rashxz the next build should be reproducible again, @linsui. 😊

**Comment by linsui** [comment]
Thanks!

**Comment by CrazyMarvin** [comment]
I just created a new release. Is F-Droid able to build (reproducible) again, @linsui?

**Comment by licaon-kter** [comment]
umm, https://gitlab.com/fdroid/fdroiddata/-/jobs/7509432023#L445 no, you added a "random" aar?

we'd need to rebuild that... or use it from maven

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/2bd3e0f4c49d5a0fa5f8c174bb49db81a270f64c

**Comment by TPS** [comment]
@CrazyMarvin Though https://github.com/Crazy-Marvin/MetadataRemover/issues/105 fixed, still not available via any FDroid-compatible repo.
