### ISSUE TITLE
documentation - supported formats

### ISSUE THREAD

**Issue by grrrrr** [Crazy-Marvin/MetadataRemover#106]
From the descriptions on github/fdroid/...  it is unclear what formats the app is able to remove metadata from or has limited support

It would be useful to include this information somewhere accessible and kept up to date as it changes

**Comment by Rashxz** [comment]
Image: PNG, JPEG
Video: AVI, MP4, MPEG, OGG, QUICKTIME, WEBM, WMV
Docs: DOCX, DOC, XLSX, XLS, ODT, ODS, PDF

@CrazyMarvin can you add this to the readme.

**Comment by grrrrr** [comment]
Thanks @Rashxz,  I can be in position update the README in a few day and send a pull request

**Comment by CrazyMarvin** [comment]
> Image: PNG, JPEG Video: AVI, MP4, MPEG, OGG, QUICKTIME, WEBM, WMV Docs: DOCX, DOC, XLSX, XLS, ODT, ODS, PDF
> 
> @CrazyMarvin can you add this to the readme.

Which audio formats are supported, @Rashxz?

**Comment by Rashxz** [comment]
> > Image: PNG, JPEG Video: AVI, MP4, MPEG, OGG, QUICKTIME, WEBM, WMV Docs: DOCX, DOC, XLSX, XLS, ODT, ODS, PDF
> > @CrazyMarvin can you add this to the readme.
> 
> Which audio formats are supported, @Rashxz?

Audio: MP4, MPEG, OGG, WEBM, X-WAV,

**Comment by CrazyMarvin** [comment]
> > > Image: PNG, JPEG Video: AVI, MP4, MPEG, OGG, QUICKTIME, WEBM, WMV Docs: DOCX, DOC, XLSX, XLS, ODT, ODS, PDF
> > > @CrazyMarvin can you add this to the readme.
> > 
> > 
> > Which audio formats are supported, @Rashxz?
> 
> Audio: MP4, MPEG, OGG, WEBM, X-WAV,

Is it possible to support AAC and MP3 too?

**Comment by Rashxz** [comment]
> > > > Image: PNG, JPEG Video: AVI, MP4, MPEG, OGG, QUICKTIME, WEBM, WMV Docs: DOCX, DOC, XLSX, XLS, ODT, ODS, PDF
> > > > @CrazyMarvin can you add this to the readme.
> > > 
> > > 
> > > Which audio formats are supported, @Rashxz?
> > 
> > 
> > Audio: MP4, MPEG, OGG, WEBM, X-WAV,
> 
> Is it possible to support AAC and MP3 too?

MP3 is supported (MPEG), let me check on AAC.

**Comment by grrrrr** [comment]
I did not get to this how evar it looks to be done so I will close.  Thanks you
