### ISSUE TITLE
Faster Sharing

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/MetadataRemover#13]
Allow other apps (Camera for instance) to share to the Metadata Remover, before ultimately sharing the picture to its intended target - this should shortcut the process.

**Comment by Giancarmine** [comment]
Hi!
I'm trying to setup the dev environment to fix this issue BUT I'm unable to decrypt the secret 

![image](https://user-images.githubusercontent.com/9807280/137624614-844469bc-91d1-4765-a720-4abbd575c4eb.png)

Any hint?
