### ISSUE TITLE
Can't see and remove MP4 metadata.


### ISSUE THREAD

**Issue by mrtaxi** [Crazy-Marvin/MetadataRemover#150]
> https://github.com/user-attachments/assets/f59ef41f-f40c-4574-99bc-c0731298f322

Android 14, OnePlus Ace 2 pro, 24/1Tb

**Comment by mrtaxi** [comment]
Sorry, it is related to f-droid version. I downloaded latest GitHub version and all ok. Thanks!

**Comment by CrazyMarvin** [comment]
I hope to fix F-Droid and IzzyOnDroid next year. 😅
