### ISSUE TITLE
Improve community guidelines

### ISSUE THREAD

**Issue by heinrichreimer** [Crazy-Marvin/MetadataRemover#16]
It would help improving community health, if we could add a Code of Conduct, general Contribution Guidelines and possibly a Contributor License Agreement.
Additionally, Issue and Pull Request templates could ease contributing for open source "newcomers"

**Comment by CrazyMarvin** [comment]
Yes, that is a nice idea. 👍
I have good experiences with a [`CONTRIBUTING.md`](https://github.com/Crazy-Marvin/FucksGiven/blob/master/CONTRIBUTING.md) and a [`CODE_OF_CONDUCT.md `](https://github.com/Crazy-Marvin/EllaTheGame/blob/master/CODE_OF_CONDUCT.md) in other repos and you are welcome to think of something for Metadata Remover.
