### ISSUE TITLE
Support Microsoft Office and LibreOffice

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/MetadataRemover#20]
Two users on Google Play mention that they would like to remove metadata from office files and I find that useful too.

**Comment by Rashxz** [comment]
Seens doable too using Apache POI

**Comment by CrazyMarvin** [comment]
> Seens doable too using Apache POI

That sounds awesome. Are you up for it, @Rashxz?

**Comment by Rashxz** [comment]
Yes, I'll work on it.

**Comment by CrazyMarvin** [comment]
Added in `v2.0.3`.  🥳
