### ISSUE TITLE
Save File On Device

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/MetadataRemover#21]
Three users from Google Play wish to save the "clean" file(s) directly on their device. 
Maybe we can use the new permission system for that so that only the users who want to save the files need to allow the storage access by Metadata Remover.

**Comment by Willt125** [comment]
Saving to device is a must-have feature if you're modifying files already on the device, because how often do you send pictures exactly once?

**Comment by CrazyMarvin** [comment]
> 
> 
> Saving to device is a must-have feature if you're modifying files already on the device, because how often do you send pictures exactly once?

We are quite busy for the next time. Would you be up for making a PR?
