### ISSUE TITLE
Support Videos

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/MetadataRemover#22]
Some users would love to remove the metadata from video files

**Comment by Rashxz** [comment]
Doable using ffmpeg. 
Heres a repo we could use https://github.com/arthenica/ffmpeg-kit

**Comment by CrazyMarvin** [comment]
> Doable using ffmpeg. Heres a repo we could use https://github.com/arthenica/ffmpeg-kit

That sounds awesome. Are you up for it, @Rashxz?

**Comment by Rashxz** [comment]
Yes, I'll work on it.

**Comment by CrazyMarvin** [comment]
Added in `v2.0.3`.  🥳
