### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/MetadataRemover#34]
- [X] [RFP](https://gitlab.com/fdroid/rfp/-/issues/926)
- [x] [Available on F-Droid](https://f-droid.org/packages/rocks.poopjournal.metadataremover/)

**Comment by IzzySoft** [comment]
Answering to your ping on the other side (I'm currently [not active at F-Droid](https://gitlab.com/fdroid/admin/-/issues/447)): Funny there's a badge in your readme pointing to a 404 on F-Droid, but no [badge pointing to mine](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :stuck_out_tongue_winking_eye:

Why would the signing certificate change? That makes updates impossible, as you might know. And the current certificate looks fine to me.

**Comment by CrazyMarvin** [comment]
> Answering to your ping on the other side (I'm currently [not active at F-Droid](https://gitlab.com/fdroid/admin/-/issues/447)): Funny there's a badge in your readme pointing to a 404 on F-Droid, but no [badge pointing to mine](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) 😜
> 
> Why would the signing certificate change? That makes updates impossible, as you might know. And the current certificate looks fine to me.

Somehow I expected to be on [F-Droid](https://f-droid.org/packages/rocks.poopjournal.metadataremover/) earlier. 🤣
I added links to [IzzyOnDroid](https://github.com/Crazy-Marvin/MetadataRemover/commit/93f9718b928d028aa32608d4120f68c9d51a1a8a) now.

I am sorry to read about the problems at the F-Droid orga.

Unfortunately I did not put the certificate into my password manager and do not have access at the moment. 🙈
I will contact Heinrich about this because he might have the keystore.

**Comment by IzzySoft** [comment]
Thanks @CrazyMarvin – looking forward to hear back from you then. And as for signing keys, recommended reading: [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss) Written by someone you might know :wink:

**Comment by CrazyMarvin** [comment]
> Thanks @CrazyMarvin – looking forward to hear back from you then. And as for signing keys, recommended reading: [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss) Written by someone you might know 😉

That is a great article from an awesome person! 😂

Heinrich was able to help me get the original signing key so upgrading for IzzyOnDroid users will be easy going. 😌

**Comment by IzzySoft** [comment]
> That is a great article from an awesome person! 😂

Thanks! :hugs: And glad you enjoyed it :smile:

> Heinrich was able to help me get the original signing key so upgrading for IzzyOnDroid users will be easy going. 😌

Yay :partying_face: Wonderful!

**Comment by IzzySoft** [comment]
Btw, thanks for adding Fastlane! Just leaving a note that your `full_description.txt` will render a bit "strange" at F-Droid, and weird with my repo (when I'd try rendering it as Markdown). Not sure what format that should be, it's quite a little mix :stuck_out_tongue_winking_eye:

* lines 5-9 would render fine as bullet-point list would you use an asterisk (`*`) instead of a check mark (`√`) as leading character
* similarly, lines 17-22 if they were preceded by an empty line (and using an asterisk)
* lines 24-27 would render as a single paragraph. If you wanted that as multiple paragraphs, those would need to be separated by empty lines between them. Same for lines 29-30 and 13-14

Of course I could take the text as-is, just replacing each line break with `<br>` as F-Droid does. But honestly, that wouldn't look half as good :wink: So I wait your decision (and maybe adjustment) before enabling the full description here.

**Comment by CrazyMarvin** [comment]
> Btw, thanks for adding Fastlane! Just leaving a note that your `full_description.txt` will render a bit "strange" at F-Droid, and weird with my repo (when I'd try rendering it as Markdown). Not sure what format that should be, it's quite a little mix 😜
> 
> * lines 5-9 would render fine as bullet-point list would you use an asterisk (`*`) instead of a check mark (`√`) as leading character
> * similarly, lines 17-22 if they were preceded by an empty line (and using an asterisk)
> * lines 24-27 would render as a single paragraph. If you wanted that as multiple paragraphs, those would need to be separated by empty lines between them. Same for lines 29-30 and 13-14
> 
> Of course I could take the text as-is, just replacing each line break with `<br>` as F-Droid does. But honestly, that wouldn't look half as good 😉 So I wait your decision (and maybe adjustment) before enabling the full description here.

Thanks for the hint, @IzzySoft. Please check if my adjustments look fine. The file is using HTML consistently now.

**Comment by IzzySoft** [comment]
Thanks! That looks fine for my repo (in which I've now set it to be rendered as Markdown). Note however that F-Droid will rather take it as-is, replacing each newline with `<br>` and then use the result as HTML – so be prepared for "blank lines" inside the bullet-point lists there. Will render absolutely fine with my repo, though, which properly converts it to HTML and then *removes* all line breaks (resulting in a single line of proper HTML to avoid fdroidserver from doing its `<br>` thingy).

**Comment by CrazyMarvin** [comment]
> Thanks! That looks fine for my repo (in which I've now set it to be rendered as Markdown). Note however that F-Droid will rather take it as-is, replacing each newline with `<br>` and then use the result as HTML – so be prepared for "blank lines" inside the bullet-point lists there. Will render absolutely fine with my repo, though, which properly converts it to HTML and then _removes_ all line breaks (resulting in a single line of proper HTML to avoid fdroidserver from doing its `<br>` thingy).

May you please open a PR with your suggestion? I am not 100% sure what you mean.

**Comment by CrazyMarvin** [comment]
Metadata Remover is available on F-Droid now. 🥳

**Comment by IzzySoft** [comment]
Congrats, @CrazyMarvin! Seeing the APK size, I'll now remove it from IzzyOnDroid – 160 MB is more than 5 times the size allotted per app here, and I'm afraid not even per-ABI builds can mitigate that. Just letting you know so you can take care for the badge. Removal will come into effect with the next sync around 6 pm UTC.

Thanks for having been at IzzyOnDroid for more than 5 years! The app first showed up there 2019-04-18 in case you wonder :wink:

**Comment by TPS** [comment]
> 160 MB is more than 5 times the size

@CrazyMarvin [A _15×_ size increase](https://github.com/Crazy-Marvin/MetadataRemover/issues/105) between patch versions?!   Any hope for a lean edition of the current app?

**Comment by CrazyMarvin** [comment]
> Congrats, @CrazyMarvin! Seeing the APK size, I'll now remove it from IzzyOnDroid – 160 MB is more than 5 times the size allotted per app here, and I'm afraid not even per-ABI builds can mitigate that. Just letting you know so you can take care for the badge. Removal will come into effect with the next sync around 6 pm UTC.
> 
> Thanks for having been at IzzyOnDroid for more than 5 years! The app first showed up there 2019-04-18 in case you wonder :wink: 

Thank you for your help. You are an inspiration, @IzzySoft! 😘
