### ISSUE TITLE
RTL layout

### ISSUE THREAD

**Issue by islam2hamy** [Crazy-Marvin/MetadataRemover#71]
Couldn't see metadata on phone with RTL language
![Screenshot_٢٠٢٤-٠٤-٠١-٠٤-٢٨-٥٠-٢١٧_rocks poopjournal metadataremover-edit](https://github.com/Crazy-Marvin/MetadataRemover/assets/7989030/74877cbb-3ed2-439c-a37e-9f56c231589b)

**Comment by CrazyMarvin** [comment]
Thanks for the report, @islam2hamy.
May you please check, @Rashxz?

**Comment by Rashxz** [comment]
Sure, already send a PR with a fix. #78

**Comment by CrazyMarvin** [comment]
> Sure, already send a PR with a fix. #78 

Awesome, thank you very much! 👍
