### ISSUE TITLE
Wrong APK in latest GitHub release

### ISSUE THREAD

**Issue by HelmetOwl** [Crazy-Marvin/MetadataRemover#79]
When you try to install the latest release's APK downloaded from GitHub, it's for an application called OMG Soundboard, not metadata remover.

**Comment by CrazyMarvin** [comment]
Oh no, you're right. Thanks for noticing. 🙈
I will fix it soon.

**Comment by CrazyMarvin** [comment]
It is fixed now, @HelmetOwl.
